DROP DATABASE DVDdb ;
CREATE DATABASE DVDdb;
USE DVDdb;

CREATE TABLE DVD(
    DVDID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(50) NOT NULL,
    ReleaseYear INT NOT NULL,
    Director VARCHAR(50) NOT NULL,
    Rating VARCHAR(6) NOT NULL,
    notes Text NOT NULL
);